name: Send Webhook on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          headers: '{"Content-Type": "application/json"}'
          body: '{"event": "push", "repository": "${{ github.repository }}"}'