
export type MonsterModelDetail = {
    monsterName: string,
    hitPoints: number,
    hitPointsRoll: string,
    strength: number,
    dexterity: number,
    constitution: number,
    intelligence: number,
    wisdom: number,
    charisma: number,
    challengeRating: number,
    xp: number,
    imageUrl: string | null,
    dnd5Native: boolean,
    passivePerception: number,
    darkvision: number | null,
    walk: number | null,
    swim: number | null,
    fly: number | null,
    alignment: string | null,
    monsterType: string,
    size: string,
    armorClass: number,
    armorType: string,
    languages: string[],
    conditionsImmunities: string[],
    monsterVulnerabilities: string[],
    monsterResistances: string[],
    monsterImunities: string[],
    specialAbilities: string[]
}